//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrazsToursWeatherWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConToStringAPIBrazsToursWeatherDB : DbContext
    {
        public ConToStringAPIBrazsToursWeatherDB()
            : base("name=ConToStringAPIBrazsToursWeatherDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WeatherForecast> WeatherForecasts { get; set; }
    }
}
